# -*- coding: UTF-8 -*-
#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: TSC.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------
# Author:       Rob King
# Changed:      03/08/2018
# Copyright:    None
# Abstract:     V2.0
#               Ported from Python 2.x to 3.7.0 with corrected deprecated code
#               when errors/warnings were found.
#----------------------------------------------------------------------------


# Include wxPython modules
import wx
import wx.grid
#import wx.animate

# Custom source
from LogTextCtrl import LogTextCtrl


# Window functions

ID_TEXT = 10000
ID_SERPORT_COMBO = 10001
ID_SERSTATUS = 10002
ID_PAL_DEFAULTS = 10003
ID_CITC_BUTTON = 10004
ID_HELP_BUTTON = 10005
ID_LOG_TEXTCTRL = 10006

def MainDlg( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.HORIZONTAL )
    
    item1 = wx.BoxSizer( wx.VERTICAL )
    
    item3 = wx.StaticBox( parent, -1, "Settings" )
    item2 = wx.StaticBoxSizer( item3, wx.VERTICAL )
    
    item4 = wx.BoxSizer( wx.HORIZONTAL )
    
    item5 = wx.StaticText( parent, ID_TEXT, "&Serial port:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.SetToolTip( wx.ToolTip("If manually entering serial port name, click away from control when finished.") )
    item4.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6 = wx.ComboBox( parent, ID_SERPORT_COMBO, "", wx.DefaultPosition, [200,-1], 
        ["COM1","COM2","/dev/ttyS0","/dev/ttyS1","/dev/ttyUSB0","/dev/ttyUSB1"] , wx.CB_DROPDOWN )
    item6.SetToolTip( wx.ToolTip("Select serial port from drop-down list or enter it directly.") )
    item4.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7 = wx.BoxSizer( wx.HORIZONTAL )
    
    item8 = wx.StaticText( parent, ID_TEXT, "Status:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item9 = wx.StaticText( parent, ID_SERSTATUS, "---", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.Add( item9, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2.Add( item7, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item10 = wx.StaticText( parent, ID_TEXT, "Pixel Colors:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item10, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item11 = wx.BoxSizer( wx.HORIZONTAL )
    parent.paletteSizer = item11
    
    item2.Add( item11, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 15 )

    item12 = wx.Button( parent, ID_PAL_DEFAULTS, "Set to &Defaults", wx.DefaultPosition, wx.DefaultSize, 0 )
    item12.SetToolTip( wx.ToolTip("Replace all 8 color palette entries with internal default values.") )
    item2.Add( item12, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item13 = wx.Button( parent, ID_CITC_BUTTON, "&Copy Image to Clipboard", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.SetToolTip( wx.ToolTip("Copy bitmap image to the system clipboard.") )
    item2.Add( item13, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item14 = wx.Button( parent, ID_HELP_BUTTON, "&Help", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.SetToolTip( wx.ToolTip("Display help on setting up your 'scope and using this program.") )
    item2.Add( item14, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item16 = wx.StaticBox( parent, -1, "Log" )
    item15 = wx.StaticBoxSizer( item16, wx.VERTICAL )
    
    item17 = LogTextCtrl( parent, ID_LOG_TEXTCTRL, "", wx.DefaultPosition, [300,300], wx.TE_MULTILINE|wx.TE_RICH|wx.TE_READONLY )
    item15.Add( item17, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item1.Add( item15, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item1, 1, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 5 )

    item19 = wx.StaticBox( parent, -1, "Screen Capture" )
    item18 = wx.StaticBoxSizer( item19, wx.VERTICAL )

    parent.capSizer = item18
    
    item0.Add( item18, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
